### ISSUE TITLE
Parallelization for training

### ISSUE THREAD

**Issue by GGJulien** [Mehooz/vision4leg#6]
Hello,

The training takes more than 24 hours! I'm wondering have you tried to implement parallelization tools such as MPI or RLLIB for this algorithm?

Thank you very much for your time.

**Comment by Mehooz** [comment]
Hi,

Thank you for pointing this out. Unfortunately, we currently believe the bottleneck of the speed is the image rendering, and using MPI can not solve the problem since the synchronization between different processes can cost a lot. So we won't suggest the MPI style for parallelization.

In my opinion, training for one day is common in the DRL area. But if you can not endure, we encourage you to figure out how to properly accelerate it :)

**Comment by GGJulien** [comment]
Thank you very much for your answer. Yeah indeed the vision part is bottle-neck
One question is there a way to stop training and running again from the previous training time? Continuing  training from the previous trained network?
